Repository Kyle1668/SRJC-CS-Club-Website, pull requests merged in 2018-04, with the labels that each got.

#6 Readme Rewrite
  README.md
Labels: enhancement

#20 Readme Updates
  .sass-cache/b84a11b95eff6988a81b39a1c8cd5119d7feacdf/index.scssc
  README.md
  source/stylesheets/index.css.map
Labels: development

#24 Andrew readme windows
  README.md
Labels: Documentation, development
